// Emits CSS custom properties from tokens.json.
//
// One source of truth. The alternative -- hand-writing the CSS variables and
// keeping them in step by discipline -- is how a palette quietly becomes a
// suggestion, which is exactly what the approval-card review caught.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = dirname(here);
const outFile = join(repoRoot, 'apps', 'desktop', 'web', 'tokens.css');

const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

/** Look up a dotted path inside the token tree. */
function lookup(path) {
  return path.split('.').reduce((node, key) => (node == null ? node : node[key]), tokens);
}

const unresolvedRefs = [];

/** A token leaf is either `{ value }` or `{ ref }` pointing at another leaf. */
function resolveValue(node, seen = new Set()) {
  if (node == null || typeof node !== 'object') return undefined;
  if (typeof node.ref === 'string') {
    if (seen.has(node.ref)) return undefined; // guard against a cycle
    seen.add(node.ref);
    const target = lookup(node.ref);
    if (target === undefined) {
      // Record it. A silently skipped reference produces a stylesheet that is
      // missing values, and a UI that is subtly unstyled -- which is exactly
      // what happened here once already. Fail loudly instead.
      unresolvedRefs.push(node.ref);
      return undefined;
    }
    return resolveValue(target, seen);
  }
  if ('value' in node) return String(node.value);
  return undefined;
}

const lines = [];

function walk(node, prefix) {
  for (const [key, child] of Object.entries(node)) {
    if (key === 'meta' || key === 'rule') continue;
    const name = prefix ? `${prefix}-${key}` : key;
    const value = resolveValue(child);
    if (value !== undefined) {
      lines.push(`  --${name}: ${value};`);
    } else if (child && typeof child === 'object') {
      walk(child, name);
    }
  }
}

walk(tokens, '');

if (unresolvedRefs.length > 0) {
  console.error(
    'BUILD FAILED: unresolved token references -> ' +
      [...new Set(unresolvedRefs)].join(', '),
  );
  console.error('Every ref must be a full dotted path from the root (e.g. color.brand.sand).');
  process.exit(1);
}

const css = `/* GENERATED by design/build-tokens.mjs -- do not edit.
 * Source of truth: design/tokens.json
 * Regenerate with: npm run build:tokens
 */

:root {
${[...new Set(lines)].join('\n')}
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);

const count = new Set(lines).size;
console.log(`tokens.css written: ${count} custom properties -> ${outFile}`);
