// Bundles the sidecar together with the policy layer.
//
// Why a bundle rather than running the TypeScript directly: the policy layer
// uses TypeScript-style directory imports (`from '../risk-classifier'`), which
// Node's ESM loader does not resolve, and Windows absolute paths need `file://`
// URLs. Bundling removes the whole class of problem and produces one file the
// shell can point at.

import { build } from 'esbuild';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [join(here, 'src', 'main.ts')],
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  outfile: join(here, 'dist', 'sidecar.mjs'),
  banner: {
    js: '// GENERATED by apps/desktop/sidecar/build.mjs -- do not edit.\n// Bundles the sidecar with the risk classifier and policy layer.',
  },
  logLevel: 'info',
});
